import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import localFont from 'next/font/local'

const localfont = localFont({ 
  src: [
    {
      path: './font/MonumentExtended-Regular.woff',
      weight: '400'
    },
    {
      path: '/font/MonumentExtended-Bold.woff',
      weight: '700'
    }
  ],
  variable: '--font-monu'
})

const chineseFont = localFont({
  src: './font/japan-font.ttf',
  variable: '--font-chinese'
})

const fraktionMonoFont = localFont({
  src: './font/FraktionMono-Regular.woff2',
  variable: '--font-fraktion'
})
export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${localfont.variable} ${chineseFont.variable} ${fraktionMonoFont.variable}`}>
            {children}
      </body>
    </html>
  )
}
